### ISSUE TITLE
Control-c does not stop optimization

### ISSUE THREAD

**Issue by grantbruer** [slimgroup/SlimOptim.jl#8]
I think this bit in the line search code catches too many exceptions.

https://github.com/slimgroup/SlimOptim.jl/blob/b9c4cec8286eb5bd7c870c1f06b9055605b8ef3a/src/linesearches.jl#L44-L49

Specifically, when I'm running an optimization interactively and want to stop it, control-c simply prints that the line search failed and then the optimization continues. Because my forward model takes several seconds to run, I can do another control-c to kill the optimization. But if my forward model was very fast, I may very well get into another line search before I can send the interrupt signal again.

Can I make a PR to add `e isa InterruptException && rethrow(e)` to this `catch`?

**Comment by mloubout** [comment]
I actually have a local change I forgot to push cuz I ran into some small debug issue as well.

```

    # Line search. Prevents it to throw error.
    try
        return ls(ϕ, dϕ, ϕdϕ, t, funRef, gtd)
    catch e
        if isa(e, LineSearchException)
            @info "Line search failed"
            return 0, funRef
        else
            throw(e)
        end
    end
```

This way it only continues if the line search ended with no solution.  Current one is indeed bad as if any of the `f/df/fdf` function error it thinks it's just the line search
